import type { LucideIcon } from 'lucide-react';
import {
  FileText,
  ImageIcon,
  QrCode,
  Search,
  Sparkles,
  Type,
  Code2,
  Calculator,
  ArrowLeftRight,
  Share2,
  Shield,
  Users,
  Zap,
  Gauge,
  Image as ImageLucide,
  FilePlus,
  Scissors,
  FileImage,
  KeyRound,
  AlignLeft,
  Braces,
  Binary,
  CalendarClock,
  HeartPulse,
  Clock,
  TrendingUp,
  Link2,
  Barcode,
  ScanLine,
  History as HistoryIcon,
  Archive,
  Scaling,
  Repeat,
  Crop,
  ShieldCheck,
  UserPlus,
  Fingerprint,
  Hash,
  CaseSensitive,
  ListOrdered,
  Pilcrow,
  Cake,
  Percent,
  Landmark,
  Receipt,
  BadgePercent,
  Utensils,
  Sigma,
  Ruler,
  Scale,
  Thermometer,
  HardDrive,
  CheckCircle2,
  FileCode2,
  Minimize2,
  Tags,
  Bot,
  Network,
  FileSearch,
  Slash,
  Globe,
  ExternalLink,
  FileJson,
  Terminal,
  Route,
  Map,
  Regex,
  Key,
  Twitter,
  Link,
} from 'lucide-react';

export type Category = {
  slug: string;
  name: string;
  count: number;
  icon: LucideIcon;
  gradient: string;
  description: string;
};

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: LucideIcon;
  gradient: string;
  badge?: string;
  isNew?: boolean;
  popularity: number;
  addedDaysAgo?: number;
};

export const categories: Category[] = [
  {
    slug: 'pdf',
    name: 'PDF Tools',
    count: 24,
    icon: FileText,
    gradient: 'from-rose-400 to-red-600',
    description: 'Merge, split, convert and optimize PDF files.',
  },
  {
    slug: 'image',
    name: 'Image Tools',
    count: 38,
    icon: ImageIcon,
    gradient: 'from-fuchsia-400 to-purple-600',
    description: 'Compress, resize and convert images instantly.',
  },
  {
    slug: 'qr-barcode',
    name: 'QR & Barcode Tools',
    count: 12,
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    description: 'Generate QR codes and barcodes for anything.',
  },
  {
    slug: 'seo',
    name: 'SEO Tools',
    count: 21,
    icon: Search,
    gradient: 'from-orange-400 to-amber-600',
    description: 'Analyze and improve your search visibility.',
  },
  {
    slug: 'ai',
    name: 'AI Tools',
    count: 18,
    icon: Sparkles,
    gradient: 'from-sky-400 to-blue-600',
    description: 'Generate text, images and ideas with AI.',
  },
  {
    slug: 'text',
    name: 'Text Tools',
    count: 30,
    icon: Type,
    gradient: 'from-cyan-400 to-blue-500',
    description: 'Count, convert, format and transform text.',
  },
  {
    slug: 'developer',
    name: 'Developer Tools',
    count: 27,
    icon: Code2,
    gradient: 'from-violet-400 to-indigo-600',
    description: 'Format, encode and debug code faster.',
  },
  {
    slug: 'calculators',
    name: 'Calculators',
    count: 19,
    icon: Calculator,
    gradient: 'from-blue-400 to-purple-500',
    description: 'Financial, health and everyday calculators.',
  },
  {
    slug: 'converters',
    name: 'Converters',
    count: 16,
    icon: ArrowLeftRight,
    gradient: 'from-indigo-400 to-blue-600',
    description: 'Convert units, files and formats with ease.',
  },
  {
    slug: 'social-media',
    name: 'Social Media Tools',
    count: 15,
    icon: Share2,
    gradient: 'from-pink-400 to-rose-600',
    description: 'Optimize posts and grow your presence.',
  },
];

export const tools: Tool[] = [
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create custom QR codes for links, text and more in seconds.',
    category: 'QR & Barcode',
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    badge: 'Popular',
    popularity: 98,
  },
  {
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate barcodes in multiple formats for products and labels.',
    category: 'QR & Barcode',
    icon: Barcode,
    gradient: 'from-emerald-400 to-green-600',
    popularity: 84,
  },
  {
    slug: 'qr-scanner',
    name: 'QR Scanner',
    description: 'Scan QR codes with your camera or decode them from an image.',
    category: 'QR & Barcode',
    icon: ScanLine,
    gradient: 'from-sky-400 to-indigo-600',
    popularity: 88,
  },
  {
    slug: 'qr-history',
    name: 'QR History',
    description: 'View, reopen and download every QR code you generated or scanned.',
    category: 'QR & Barcode',
    icon: HistoryIcon,
    gradient: 'from-slate-400 to-slate-600',
    popularity: 70,
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size without losing visible quality.',
    category: 'Image',
    icon: Gauge,
    gradient: 'from-fuchsia-400 to-purple-600',
    badge: 'Popular',
    popularity: 95,
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to exact dimensions with aspect ratio lock.',
    category: 'Image',
    icon: Scaling,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 86,
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between JPG, PNG and WEBP formats.',
    category: 'Image',
    icon: Repeat,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 82,
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images into square, 16:9, 4:3 or circle shapes.',
    category: 'Image',
    icon: Crop,
    gradient: 'from-amber-400 to-orange-600',
    badge: 'New',
    popularity: 80,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF files into a single document.',
    category: 'PDF',
    icon: FilePlus,
    gradient: 'from-rose-400 to-red-600',
    badge: 'Popular',
    popularity: 92,
  },
  {
    slug: 'pdf-split',
    name: 'PDF Split',
    description: 'Extract pages or split a PDF into separate files.',
    category: 'PDF',
    icon: Scissors,
    gradient: 'from-rose-400 to-pink-600',
    popularity: 78,
  },
  {
    slug: 'pdf-compress',
    name: 'PDF Compress',
    description: 'Reduce PDF file size with three compression levels.',
    category: 'PDF',
    icon: Archive,
    gradient: 'from-red-400 to-orange-600',
    badge: 'Popular',
    popularity: 89,
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG and PNG images into a clean PDF document.',
    category: 'PDF',
    icon: FileImage,
    gradient: 'from-red-400 to-rose-600',
    popularity: 81,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong, secure and random passwords instantly.',
    category: 'Security',
    icon: KeyRound,
    gradient: 'from-cyan-400 to-blue-500',
    badge: 'Popular',
    popularity: 90,
  },
  {
    slug: 'password-strength-checker',
    name: 'Password Strength Checker',
    description: 'Analyze password strength and estimate crack time.',
    category: 'Security',
    icon: ShieldCheck,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 85,
  },
  {
    slug: 'username-generator',
    name: 'Username Generator',
    description: 'Generate unique random usernames with prefixes and suffixes.',
    category: 'Security',
    icon: UserPlus,
    gradient: 'from-violet-400 to-purple-600',
    popularity: 82,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUID v4 identifiers in bulk.',
    category: 'Security',
    icon: Fingerprint,
    gradient: 'from-blue-400 to-indigo-600',
    popularity: 78,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences and reading time.',
    category: 'Text',
    icon: AlignLeft,
    gradient: 'from-sky-400 to-cyan-500',
    popularity: 88,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify and validate JSON with syntax highlighting.',
    category: 'Developer',
    icon: Braces,
    gradient: 'from-violet-400 to-indigo-600',
    badge: 'Popular',
    popularity: 93,
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    description: 'Encode and decode text or files to and from Base64.',
    category: 'Developer',
    icon: Binary,
    gradient: 'from-indigo-400 to-blue-600',
    popularity: 80,
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months and days.',
    category: 'Calculators',
    icon: CalendarClock,
    gradient: 'from-blue-400 to-purple-500',
    popularity: 86,
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index and understand your range.',
    category: 'Calculators',
    icon: HeartPulse,
    gradient: 'from-purple-400 to-blue-600',
    popularity: 82,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder',
    description: 'Encode and decode URLs to safely pass special characters.',
    category: 'Developer',
    icon: Link2,
    gradient: 'from-indigo-400 to-cyan-600',
    popularity: 76,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting.',
    category: 'Developer',
    icon: Regex,
    gradient: 'from-violet-400 to-purple-600',
    badge: 'New',
    popularity: 78,
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, words and spaces in your text instantly.',
    category: 'Text',
    icon: Hash,
    gradient: 'from-sky-400 to-blue-500',
    popularity: 84,
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from any text instantly.',
    category: 'Text',
    icon: ListOrdered,
    gradient: 'from-teal-400 to-emerald-600',
    popularity: 72,
  },
  {
    slug: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines alphabetically, reverse or remove empty lines.',
    category: 'Text',
    icon: ListOrdered,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 70,
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text in words, sentences or paragraphs.',
    category: 'Text',
    icon: Pilcrow,
    gradient: 'from-amber-400 to-yellow-600',
    popularity: 76,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Switch text between upper, lower, title, sentence and toggle case.',
    category: 'Text',
    icon: CaseSensitive,
    gradient: 'from-sky-400 to-indigo-500',
    badge: 'New',
    popularity: 80,
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months and days.',
    category: 'Calculator',
    icon: Cake,
    gradient: 'from-pink-400 to-rose-600',
    badge: 'Popular',
    popularity: 88,
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index from height and weight.',
    category: 'Calculator',
    icon: HeartPulse,
    gradient: 'from-red-400 to-pink-600',
    popularity: 85,
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, increases and decreases instantly.',
    category: 'Calculator',
    icon: Percent,
    gradient: 'from-blue-400 to-cyan-600',
    popularity: 84,
  },
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Calculate monthly loan EMI, total interest and payment.',
    category: 'Calculator',
    icon: Landmark,
    gradient: 'from-emerald-400 to-green-600',
    badge: 'Popular',
    popularity: 90,
  },
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Calculate GST inclusive and exclusive amounts instantly.',
    category: 'Calculator',
    icon: Receipt,
    gradient: 'from-indigo-400 to-blue-600',
    popularity: 82,
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate discount amounts and final prices after savings.',
    category: 'Calculator',
    icon: BadgePercent,
    gradient: 'from-amber-400 to-orange-600',
    popularity: 80,
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips and split bills between any number of people.',
    category: 'Calculator',
    icon: Utensils,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 78,
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    description: 'Calculate simple interest on loans and investments.',
    category: 'Calculator',
    icon: TrendingUp,
    gradient: 'from-lime-400 to-green-600',
    popularity: 75,
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest with compounding frequency.',
    category: 'Calculator',
    icon: Sigma,
    gradient: 'from-violet-400 to-purple-600',
    popularity: 77,
  },
  {
    slug: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced calculator with trig, log and exponential functions.',
    category: 'Calculator',
    icon: Calculator,
    gradient: 'from-slate-400 to-gray-600',
    badge: 'New',
    popularity: 83,
  },
  {
    slug: 'length-converter',
    name: 'Length Converter',
    description: 'Convert between metres, feet, inches, miles and more.',
    category: 'Converter',
    icon: Ruler,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 82,
  },
  {
    slug: 'weight-converter',
    name: 'Weight Converter',
    description: 'Convert between kilograms, pounds, ounces and tonnes.',
    category: 'Converter',
    icon: Scale,
    gradient: 'from-orange-400 to-amber-600',
    popularity: 80,
  },
  {
    slug: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit and Kelvin.',
    category: 'Converter',
    icon: Thermometer,
    gradient: 'from-red-400 to-orange-600',
    popularity: 81,
  },
  {
    slug: 'time-converter',
    name: 'Time Converter',
    description: 'Convert between seconds, minutes, hours, days and weeks.',
    category: 'Converter',
    icon: Clock,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 76,
  },
  {
    slug: 'data-storage-converter',
    name: 'Data Storage Converter',
    description: 'Convert between bytes, KB, MB, GB, TB and PB.',
    category: 'Converter',
    icon: HardDrive,
    gradient: 'from-teal-400 to-emerald-600',
    popularity: 74,
  },
  {
    slug: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON and find syntax errors instantly.',
    category: 'Developer',
    icon: CheckCircle2,
    gradient: 'from-green-400 to-emerald-600',
    popularity: 79,
  },
  {
    slug: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Beautify and minify HTML code with proper indentation.',
    category: 'Developer',
    icon: FileCode2,
    gradient: 'from-orange-400 to-red-600',
    popularity: 76,
  },
  {
    slug: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS to reduce file size and improve load speed.',
    category: 'Developer',
    icon: Minimize2,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 73,
  },
  {
    slug: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code to reduce file size instantly.',
    category: 'Developer',
    icon: Terminal,
    gradient: 'from-yellow-400 to-amber-600',
    popularity: 75,
  },
  {
    slug: 'sha256-hash-generator',
    name: 'SHA256 Hash Generator',
    description: 'Generate SHA-256 hashes from any text input.',
    category: 'Developer',
    icon: Fingerprint,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 72,
  },
  {
    slug: 'md5-hash-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hashes from any text input instantly.',
    category: 'Developer',
    icon: Key,
    gradient: 'from-rose-400 to-pink-600',
    popularity: 70,
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for title, description and more.',
    category: 'SEO Tools',
    icon: Tags,
    gradient: 'from-orange-400 to-amber-600',
    badge: 'Popular',
    popularity: 85,
  },
  {
    slug: 'open-graph-generator',
    name: 'Open Graph Generator',
    description: 'Generate Open Graph tags for social media sharing.',
    category: 'SEO Tools',
    icon: Share2,
    gradient: 'from-blue-400 to-indigo-600',
    popularity: 80,
  },
  {
    slug: 'twitter-card-generator',
    name: 'Twitter Card Generator',
    description: 'Generate Twitter Card meta tags for better link previews.',
    category: 'SEO Tools',
    icon: Twitter,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 78,
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files to control search engine crawlers.',
    category: 'SEO Tools',
    icon: Bot,
    gradient: 'from-slate-400 to-gray-600',
    popularity: 76,
  },
  {
    slug: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemaps for search engine indexing.',
    category: 'SEO Tools',
    icon: Network,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 77,
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    description: 'Analyze keyword density and frequency in your content.',
    category: 'SEO Tools',
    icon: FileSearch,
    gradient: 'from-purple-400 to-violet-600',
    popularity: 74,
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate SEO-friendly URL slugs from any text.',
    category: 'SEO Tools',
    icon: Slash,
    gradient: 'from-cyan-400 to-blue-600',
    popularity: 73,
  },
  {
    slug: 'canonical-url-generator',
    name: 'Canonical URL Generator',
    description: 'Generate canonical URL tags to avoid duplicate content.',
    category: 'SEO Tools',
    icon: Link,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 71,
  },
  {
    slug: 'search-snippet-preview',
    name: 'Search Snippet Preview',
    description: 'Preview how your page appears in Google search results.',
    category: 'SEO Tools',
    icon: Search,
    gradient: 'from-indigo-400 to-blue-600',
    badge: 'New',
    popularity: 82,
  },
  {
    slug: 'redirect-checker',
    name: 'Redirect Checker',
    description: 'Check URL redirect chains and HTTP status codes.',
    category: 'SEO Tools',
    icon: Route,
    gradient: 'from-amber-400 to-orange-600',
    popularity: 70,
  },
];

export const latestTools: Tool[] = [
  {
    slug: 'color-picker',
    name: 'Color Picker',
    description: 'Grab colors and copy HEX, RGB and HSL values.',
    category: 'Image',
    icon: ImageLucide,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 64,
    addedDaysAgo: 1,
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see live rendered output instantly.',
    category: 'Text',
    icon: Type,
    gradient: 'from-cyan-400 to-blue-500',
    isNew: true,
    popularity: 58,
    addedDaysAgo: 3,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Switch text between upper, lower, title and more.',
    category: 'Text',
    icon: Type,
    gradient: 'from-sky-400 to-indigo-500',
    isNew: true,
    popularity: 52,
    addedDaysAgo: 5,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting.',
    category: 'Developer',
    icon: Code2,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 60,
    addedDaysAgo: 7,
  },
];

export const mostPopularTools: Tool[] = [
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size without losing visible quality.',
    category: 'Image',
    icon: Gauge,
    gradient: 'from-fuchsia-400 to-purple-600',
    popularity: 95,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify and validate JSON instantly.',
    category: 'Developer',
    icon: Braces,
    gradient: 'from-violet-400 to-indigo-600',
    popularity: 93,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF files into one document.',
    category: 'PDF',
    icon: FilePlus,
    gradient: 'from-rose-400 to-red-600',
    popularity: 92,
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create custom QR codes for links and text.',
    category: 'QR & Barcode',
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 98,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong, secure passwords instantly.',
    category: 'Text',
    icon: KeyRound,
    gradient: 'from-cyan-400 to-blue-500',
    popularity: 90,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters and reading time.',
    category: 'Text',
    icon: AlignLeft,
    gradient: 'from-sky-400 to-cyan-500',
    popularity: 88,
  },
];

export type Stat = {
  value: string;
  label: string;
  icon: LucideIcon;
};

export const stats: Stat[] = [
  { value: '500+', label: 'Free Tools', icon: Zap },
  { value: '1M+', label: 'Monthly Users', icon: Users },
  { value: 'Fast', label: '& Secure', icon: Shield },
  { value: 'No Sign-up', label: 'Required', icon: Gauge },
];

export function getToolsByCategory(categoryName: string): Tool[] {
  const cat = categories.find((c) => c.name === categoryName || c.slug === categoryName);
  if (!cat) return [];
  const aliases: Record<string, string[]> = {
    'PDF Tools': ['PDF'],
    'Image Tools': ['Image'],
    'QR & Barcode Tools': ['QR & Barcode'],
    'SEO Tools': ['SEO Tools'],
    'Text Tools': ['Text'],
    'Developer Tools': ['Developer'],
    'Calculators': ['Calculators', 'Calculator'],
    'Converters': ['Converter', 'Converters'],
    'AI Tools': ['AI'],
    'Social Media Tools': ['Social Media', 'Social'],
  };
  const matches = aliases[cat.name] || [cat.name, cat.slug];
  return tools.filter((t) => matches.includes(t.category));
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(slug: string, count = 3): Tool[] {
  const current = getToolBySlug(slug);
  if (!current) return tools.slice(0, count);
  const sameCategory = tools.filter(
    (t) => t.slug !== slug && t.category === current.category
  );
  const others = tools.filter(
    (t) => t.slug !== slug && t.category !== current.category
  );
  return [...sameCategory, ...others].slice(0, count);
}
